const Data = [
  {
    img: "https://res.cloudinary.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/bxvehmjybbautqoy0j0m",
    naem: "hydrabadi biryani",
    description: "asin greatest biryani",
    price: "400rs",
    min: "30",
    max: "40",
    payment: "Accept online payments only",
    rating: 4,
    votes: "8484",
    review: "532",
  },
  {
    img: "https://res.cloudinary.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/bxvehmjybbautqoy0j0m",
    naem: "hydrabadi biryani",
    description: "asin greatest biryani",
    price: "400rs",
    min: "30",
    max: "40",
    payment: "Accept online payments only",
    rating: 5,
    votes: "8484",
    review: "532",
  },
  {
    img: "https://res.cloudinary.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/bxvehmjybbautqoy0j0m",
    naem: "hydrabadi biryani",
    description: "asin greatest biryani",
    price: "400rs",
    min: "30",
    max: "40",
    payment: "Accept online payments only",
    rating: 2,
    votes: "8484",
    review: "532",
  },
  {
    img: "https://res.cloudinary.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/bxvehmjybbautqoy0j0m",
    naem: "hydrabadi biryani",
    description: "asin greatest biryani",
    price: "400rs",
    min: "30",
    max: "40",
    payment: "Accept online payments only",
    rating: 3,
    votes: "8484",
    review: "532",
  },
  {
    img: "https://res.cloudinary.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/bxvehmjybbautqoy0j0m",
    naem: "hydrabadi biryani",
    description: "asin greatest biryani",
    price: "400rs",
    min: "30",
    max: "40",
    payment: "Accept online payments only",
    rating: 1,
    votes: "8484",
    review: "532",
  },
];
export default Data;
